#!/bin/bash

GREEN='\033[0;32m'
RED="\033[0;31m"
NC="\033[0m"

function p_red() {
  printf "\n${RED}$1${NC}\n"
}
function p_green() {
  printf "\n${GREEN}$1${NC}\n"
}

function install() {
  p_red "Updating apt-get..."
  sudo apt-get update

  p_red "Installing curl..."
  sudo apt-get install curl

  p_red "Installing nodejs..."
  sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  sudo apt-get install -y nodejs

  p_red "Installing nvm..."
  sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

  p_red "Installing docker..."
  sudo apt-get install \
      apt-transport-https \
      ca-certificates \
      curl \
      software-properties-common
  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) \
     stable"
  sudo apt-get install docker-ce
  sudo usermod -aG docker ${USER}

  p_red "Installing python-pip..."
  sudo apt-get -y install python-pip

  p_red "Installing docker-compose..."
  sudo pip install docker-compose

  p_red "Installing yarn..."
  sudo npm install -g yarn

  p_red "Installing atom..."
  sudo add-apt-repository ppa:webupd8team/atom
  sudo apt-get update
  sudo apt-get install atom

  p_red "Installing atom packages..."
  sudo apm install --packages-file atom/packages.txt

  p_red "Installing chrome..."
  sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  sudo apt-get update
  sudo apt-get install google-chrome-stable -y

  p_red "Installing unzip..."
  sudo apt-get install unzip

  p_red "Installing fonts:"
  p_red " > Operator Mono..."
  sudo mkdir -p /usr/share/fonts/truetype/operator-mono
  sudo unzip .atom/OperatorMono.zip -d /usr/share/fonts/truetype/operator-mono
  p_red " > Powerline fonts for agnoster..."
  git clone https://github.com/powerline/fonts.git
  cd fonts
  sudo bash install.sh
  cd ..
  rm -rf fonts
  sudo fc-cache -f -v

  p_red "Installing terminator..."
  sudo add-apt-repository ppa:gnome-terminator
  sudo apt-get update
  sudo apt-get install terminator

  p_red "Installing zsh..."
  sudo apt-get install zsh

  p_red "Installing Oh My Zsh..."
  sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}

function copyDotFiles() {
  p_red "Copying dot files..."
  cp git/.gitconfig ~/
  cp zsh/.zshrc ~/
  cp zsh/agnoster.zsh-theme ~/.oh-my-zsh/themes
  cp terminator/config ~/.config/terminator
  cp atom/config.cson ~/.atom
  cp atom/styles.less ~/.atom
}

install
copyDotFiles

p_green "Done! Let's Rock!"
