#!/bin/bash

GREEN='\033[0;32m'
NC="\033[0m"

function p_green() {
  printf "\n${GREEN}$1${NC}\n\n"
}

function update() {
  sudo cp ~/.gitconfig ../git
  sudo cp ~/.zshrc ../zsh
  sudo cp ~/.oh-my-zsh/themes/agnoster.zsh-theme ../zsh
  sudo cp ~/.config/terminator/config ../terminator
  sudo cp ~/.atom/config.cson ../atom
  sudo cp ~/.atom/styles.less ../atom
  p_green "All files have been updated! Commit your changes."
}

update
