#!/bin/bash

GREEN='\033[0;32m'
NC="\033[0m"

function p_green() {
  printf "\n${GREEN}$1${NC}\n\n"
}

function update() {
  cp ~/.gitconfig ${PWD}/git
  cp ~/.zshrc ${PWD}/zsh
  cp ~/.oh-my-zsh/themes/agnoster.zsh-theme ${PWD}/zsh
  zp ~/.config/terminator/config ${PWD}/terminator
  cp ~/.atom/config.cson ${PWD}/atom
  cp ~/.atom/styles.less ${PWD}/atom
  p_green "All files have been updated! Commit your changes."
}

update
