#!/bin/bash

GREEN='\033[0;32m'
RED="\033[0;31m"
NC="\033[0m"

function p_red() {
  printf "\n${RED}$1${NC}\n"
}

function p_green() {
  printf "\n${GREEN}$1${NC}\n"
}

p_red "Copying dot files..."

sudo cp ../git/.gitconfig ~/
sudo cp ../zsh/.zshrc ~/
sudo cp ../zsh/agnoster.zsh-theme ~/.oh-my-zsh/themes

sudo mkdir ~/.config/terminator
sudo cp ../terminator/config ~/.config/terminator
sudo cp ../vscode/settings.json ~/.config/Code/User

sudo touch ~/.gitconfig
sudo touch ~/.zshrc
sudo touch ~/.oh-my-zsh/themes/agnoster.zsh-theme
sudo touch ~/.config/terminator/config

sudo cp ~/.config/Code/User
sudo touch ~/.config/Code/User

p_green "Done!"
