#!/bin/bash

GREEN='\033[0;32m'
RED="\033[0;31m"
NC="\033[0m"

function p_red() {
  printf "\n${RED}$1${NC}\n"
}
function p_green() {
  printf "\n${GREEN}$1${NC}\n"
}

p_red "Updating apt-get..."
sudo apt-get update

p_red "Installing curl..."
sudo apt-get install curl

p_red "Installing nodejs..."
sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

p_red "Installing nvm..."
sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

p_red "Installing mongodb..."
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
sudo apt-get install -y mongodb-org
sudo echo "[Unit]
Description=High-performance, schema-free document-oriented database
After=network.target

[Service]
User=mongodb
ExecStart=/usr/bin/mongod --quiet --config /etc/mongod.conf

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/mongodb.service
sudo systemctl start mongodb

p_red "Installing docker..."
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get install docker-ce
sudo usermod -aG docker ${USER}

p_red "Installing python-pip..."
sudo apt-get -y install python-pip

p_red "Installing docker-compose..."
sudo pip install docker-compose

p_red "Installing yarn..."
sudo npm install -g yarn

p_red "Installing neovim..."
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get install neovim

p_red "Installing vim-plug..."
sudo curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

p_red "Installing VSCode..."
sudo curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt-get update
sudo apt-get install code

# p_red "Installing atom..."
# sudo add-apt-repository ppa:webupd8team/atom
# sudo apt-get update
# sudo apt-get install atom

# p_red "Installing atom packages..."
# sudo apm install --packages-file atom/packages.txt

p_red "Installing chrome..."
sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo apt-get update
sudo apt-get install google-chrome-stable -y

p_red "Installing unzip..."
sudo apt-get install unzip

p_red "Installing fonts:"
p_red " > Operator Mono..."
sudo mkdir -p /usr/share/fonts/truetype/operator-mono
sudo unzip atom/OperatorMono.zip -d /usr/share/fonts/truetype/operator-mono
p_red " > Powerline fonts for agnoster..."
git clone https://github.com/powerline/fonts.git
cd fonts
sudo bash install.sh
cd ..
rm -rf fonts
sudo fc-cache -f -v

p_red "Installing terminator..."
sudo add-apt-repository ppa:gnome-terminator
sudo apt-get update
sudo apt-get install terminator

p_red "Installing hyper js..."
sudo apt-get install gdebi
sudo wget https://hyper-updates.now.sh/download/linux_deb

p_red "Installing zsh..."
sudo apt-get install zsh
chsh -s $(which zsh)

p_red "Installing Oh My Zsh..."
sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

p_red "Installing xclip..."
sudo apt-get install xclip

p_red "Generating SSH keys for Github..."
ssh-keygen -t rsa -b 4096 -C "thiagomunhozmedeiros@gmail.com"
ssh-add ~/.ssh/id_rsa
xclip -sel clip < ~/.ssh/id_rsa.pub

p_green "SSH keys copied to clipboard! Paste into your Github!"

p_green "Done! Let's Rock!"
